var searchData=
[
  ['getdistance',['GetDistance',['../classubxsec_1_1VertexCheck.html#a2cf14a77ddd16b2fd282e2748ed4a3d9',1,'ubxsec::VertexCheck']]],
  ['getlongesttrackfromtpcobj',['GetLongestTrackFromTPCObj',['../classUBXSecHelper.html#a76b009afef0cc69f281ca3215a901f35',1,'UBXSecHelper']]],
  ['getnumberofhitsperplane',['GetNumberOfHitsPerPlane',['../classUBXSecHelper.html#a5d811318d7fb66ab5e1816453c017e63',1,'UBXSecHelper']]],
  ['getnupfp',['GetNuPFP',['../classUBXSecHelper.html#a1803584104e1b6f618fe86b28aec1927',1,'UBXSecHelper']]],
  ['getnuvertexfromtpcobject',['GetNuVertexFromTPCObject',['../classUBXSecHelper.html#a0ffc9245fc9813c18a1880d7e6f0aefe',1,'UBXSecHelper::GetNuVertexFromTPCObject(art::Event const &amp;e, std::string _particleLabel, lar_pandora::PFParticleVector pfp_v, double *reco_nu_vtx)'],['../classUBXSecHelper.html#a092b41510117ee216ea323ea46695e1b',1,'UBXSecHelper::GetNuVertexFromTPCObject(art::Event const &amp;e, std::string _particleLabel, lar_pandora::PFParticleVector pfp_v, recob::Vertex &amp;reco_nu_vtx)']]],
  ['getqcluster',['GetQCluster',['../classNeutrinoFlashMatch.html#aa511b92472bb70883c5a666293be1da3',1,'NeutrinoFlashMatch']]],
  ['getrecototruematches',['GetRecoToTrueMatches',['../classUBXSecHelper.html#a0708dbe6fb5f3ea0f200362887473e36',1,'UBXSecHelper::GetRecoToTrueMatches(const lar_pandora::PFParticlesToHits &amp;recoParticlesToHits, const lar_pandora::HitsToMCParticles &amp;trueHitsToParticles, lar_pandora::MCParticlesToPFParticles &amp;matchedParticles, lar_pandora::MCParticlesToHits &amp;matchedHits)'],['../classUBXSecHelper.html#a111c32be3cab634ffacbfa03e7ea789b',1,'UBXSecHelper::GetRecoToTrueMatches(const lar_pandora::PFParticlesToHits &amp;recoParticlesToHits, const lar_pandora::HitsToMCParticles &amp;trueHitsToParticles, lar_pandora::MCParticlesToPFParticles &amp;matchedParticles, lar_pandora::MCParticlesToHits &amp;matchedHits, PFParticleSet &amp;recoVeto, MCParticleSet &amp;trueVeto, bool _recursiveMatching)']]],
  ['getsliceorigin',['GetSliceOrigin',['../classUBXSecHelper.html#ade125cef08f3f9ab1562556e7ae977d1',1,'UBXSecHelper']]],
  ['gettpcobjects',['GetTPCObjects',['../classUBXSecHelper.html#a36ef4a258300c98061cd01782157433b',1,'UBXSecHelper::GetTPCObjects(art::Event const &amp;e, std::string _particleLabel, std::vector&lt; lar_pandora::PFParticleVector &gt; &amp;pfp_v_v, std::vector&lt; lar_pandora::TrackVector &gt; &amp;track_v_v)'],['../classUBXSecHelper.html#a900fbd13023a46b8d3c0a38aae84a10b',1,'UBXSecHelper::GetTPCObjects(lar_pandora::PFParticleVector pfParticleList, lar_pandora::PFParticlesToTracks pfParticleToTrackMap, lar_pandora::PFParticlesToVertices pfParticleToVertexMap, std::vector&lt; lar_pandora::PFParticleVector &gt; &amp;pfp_v_v, std::vector&lt; lar_pandora::TrackVector &gt; &amp;track_v_v)']]]
];
